### ISSUE TITLE
CReDo Milestone Specific Hotfixes

### ISSUE THREAD

**Issue by Ushcode** [cambridge-cares/TheWorldAvatar#1401]
- [x] Restore legend for failure states and weather types
- [x] Fix the Connections layer tree Icon
- [x] Change default from 3D maps to 2D maps
- [x] Typos in scenario description
- [ ] Toggle a full network in one click

**Comment by Ushcode** [comment]
- [ ] Add option to optional specify an icon (same way as specifying a whole layer icon) "sidebar-icon"

**Comment by Ushcode** [comment]
- [ ] Layer names of mapbox native road tiles
- [ ] Go for old legend descriptions of failures
- [ ] Remove multiple flood styles, blue 
- [x] Name of Hazard
- [ ] Correctly find landing page icon
- [ ] Properly sanitize icons passed to mapbox with ASSET_PREFIX
